version: '3'
services:
  postgres:
    image: 'postgres:alpine'
    environment:
      - POSTGRES_PASSWORD=postgres_password
  redis:
    image: 'redis'
    command: 'redis-server --protected-mode no'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379
  api:
    build:
      context: ./server
      dockerfile: Dockerfile.dev

    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - REDIST_HOST=redis
      - REDIST_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./client:/app
  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./worker:/app
  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports: 
      - '3050:80'

